name: Deploy Laravel Without Git (Rsync Only Changed Files)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.22'
        extensions: mbstring, bcmath, intl, pdo_mysql
        tools: composer

    # 3. Install dependencies
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    # 4. Sync changed files (skip .env, storage, .git, bootstrap/cache)
    - name: Sync changed files to server
      uses: burnett01/rsync-deployments@7.0.2
      with:
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}
        path: "./"
        remote_path: ${{ secrets.SERVER_PATH }}
        switches: "-avz --delete --exclude='.env' --exclude='storage/'   --exclude='.git/' --exclude='bootstrap/cache/' --exclude='/public'  --no-perms --checksum"

    # 5. Run Laravel Artisan commands12

    - name: Run Laravel commands on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ${{ secrets.SERVER_PATH }}
          # Ensure permissions are correct
          sudo chown -R ${{ secrets.SERVER_USER }} storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
          # Clear caches
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
          # Recreate storage link if needed
          php artisan storage:link
          sudo chown -R www-data:www-data /var/www/irad.smarthr.co.tz/public/contracts
          sudo chmod -R 775 /var/www/irad.smarthr.co.tz/public/contracts

